/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const allowMultipleToast: typeof import('vant/es')['allowMultipleToast']
  const showDialog: typeof import('vant/es')['showDialog']
  const showToast: typeof import('vant/es')['showToast']
}
